version: "3.9"

services:
  web:
    restart: always
    build:
      context: ./UsersGroupsApp/
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./UsersGroupsApp/:/test-task-app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db_psql

  db_psql:
    restart: always
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strongpass
      - POSTGRES_DB=django_db

  frontend:
    restart: always
    command : npm start
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
  postgres_data:
